copperItems:
  - COPPER_INGOT
  - RAW_COPPER
copperBlocks:
  - COPPER_BLOCK
  - CUT_COPPER
  - EXPOSED_COPPER
  - WEATHERED_COPPER
  - OXIDIZED_COPPER
  - CUT_COPPER_SLAB
  - EXPOSED_CUT_COPPER
  - WEATHERED_CUT_COPPER
  - OXIDIZED_CUT_COPPER
  - CUT_COPPER_STAIRS
  - EXPOSED_CUT_COPPER_STAIRS
  - WEATHERED_CUT_COPPER_STAIRS
  - OXIDIZED_CUT_COPPER_STAIRS
  - WAXED_COPPER_BLOCK
  - WAXED_CUT_COPPER
  - COPPER_ORE
  - DEEPSLATE_COPPER_ORE
  - WAXED_EXPOSED_COPPER
  - WAXED_WEATHERED_COPPER
  - WAXED_OXIDIZED_COPPER
  - WAXED_CUT_COPPER_SLAB
  - WAXED_EXPOSED_CUT_COPPER
  - WAXED_WEATHERED_CUT_COPPER
  - WAXED_OXIDIZED_CUT_COPPER
  - WAXED_CUT_COPPER_STAIRS
  - WAXED_EXPOSED_CUT_COPPER_STAIRS
  - WAXED_WEATHERED_CUT_COPPER_STAIRS
  - WAXED_OXIDIZED_CUT_COPPER_STAIRS
redstoneItems:
  - REDSTONE
redstoneBlocks:
  - REDSTONE_ORE
  - REDSTONE_BLOCK
  - DEEPSLATE_REDSTONE_ORE
  - REDSTONE_WIRE
emeraldItems:
  - EMERALD
emeraldBlocks:
  - EMERALD_ORE
  - EMERALD_BLOCK
  - DEEPSLATE_EMERALD_ORE
quartzItems:
  - QUARTZ
quartzBlocks:
  - NETHER_QUARTZ_ORE
lapisItems:
  - LAPIS_LAZULI
lapisBlocks:
  - LAPIS_ORE
  - DEEPSLATE_LAPIS_ORE
  - LAPIS_BLOCK
coalItems:
  - COAL
  - CHARCOAL
coalBlocks:
  - COAL_ORE
  - DEEPSLATE_COAL_ORE
  - COAL_BLOCK
goldItems:
  - GOLD_NUGGET
  - GOLD_INGOT
  - RAW_GOLD
  - GOLDEN_PICKAXE
  - GOLDEN_AXE
  - GOLDEN_SHOVEL
  - GOLDEN_SWORD
  - GOLDEN_HELMET
  - GOLDEN_CHESTPLATE
  - GOLDEN_LEGGINGS
  - GOLDEN_BOOTS
  - GOLDEN_HOE
goldBlocks:
  - RAW_GOLD_BLOCK
  - NETHER_GOLD_ORE
  - GOLD_ORE
  - DEEPSLATE_GOLD_ORE
  - GOLD_BLOCK
ironItems:
  - IRON_INGOT
  - RAW_IRON
  - IRON_PICKAXE
  - IRON_AXE
  - IRON_SHOVEL
  - IRON_SWORD
  - IRON_HELMET
  - IRON_CHESTPLATE
  - IRON_LEGGINGS
  - IRON_BOOTS
  - IRON_HOE
ironBlocks:
  - RAW_IRON_BLOCK
  - IRON_ORE
  - DEEPSLATE_IRON_ORE
  - IRON_BLOCK
diamondItems:
  - DIAMOND
  - DIAMOND_PICKAXE
  - DIAMOND_AXE
  - DIAMOND_SHOVEL
  - DIAMOND_SWORD
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - DIAMOND_HOE
diamondBlocks:
  - DIAMOND_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DIAMOND_BLOCK
netheriteItems:
  - NETHERITE_SCRAP
  - NETHERITE_INGOT
  - NETHERITE_PICKAXE
  - NETHERITE_AXE
  - NETHERITE_SHOVEL
  - NETHERITE_SWORD
  - NETHERITE_HELMET
  - NETHERITE_CHESTPLATE
  - NETHERITE_LEGGINGS
  - NETHERITE_BOOTS
  - NETHERITE_HOE
netheriteBlocks:
  - ANCIENT_DEBRIS
  - NETHERITE_BLOCK